steps:
  # group up all the steps that are related to the quality assurance of the code
  - group: ':mag: QA'
    id: quality_assurance
    steps:
    - key: lint
      label: ':golang: vet'
      command: cd hello && go vet ./...
      plugins:
        - docker-compose#v5.4.0:
            run: app

    - key: test
      label: ':golang: test'
      command: 
        - cd hello && go test -v -count=1 -cover ./... -coverprofile=coverage.txt -covermode=atomic
      artifact_paths:
        - 'coverage.txt' # upload the coverage report as an artifact
      plugins:
        - docker-compose#v5.4.0:
            run: app

  # build the application after the quality assurance steps are done
  - key: build
    label: ':golang: build'
    command: "cd hello && go build -o hello"
    artifact_paths:
      - 'hello/hello' # upload the built application as an artifact
    plugins:
      - docker-compose#v5.4.0:
          run: app
    depends_on: quality_assurance

  - block: "What is your name?"
    prompt: "Enter Your First Name"
    fields: 
      - text: "First Name"
        key: "first_name"
        required: true 

  - key: run
    label: ':runner: Run'
    command:
      - buildkite-agent artifact download hello/hello .
      - chmod +x ./hello/hello
      - ./hello/hello ${first_name}
